# Generated by Django 4.0.1 on 2022-02-09 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cutomers',
            new_name='customers',
        ),
    ]
